/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Campaign {
  id: Generated<string>;
  name: string;
  tenant_id: string;
}

export interface ClaimCurrent {
  campaign_id: string;
  claim_id: string;
  object: Json;
  predicate: string;
  subject_id: string;
  tenant_id: string;
  version: number;
}

export interface ClaimEmbedding {
  claim_id: string;
  embedding: string;
  tenant_id: string;
}

export interface ClaimVersion {
  campaign_id: string;
  claim_id: string;
  object: Json;
  predicate: string;
  recorded_at: Generated<Timestamp>;
  subject_id: string;
  tenant_id: string;
  version: number;
}

export interface Entity {
  campaign_id: string;
  custom: Generated<Json>;
  display_name: string;
  id: Generated<string>;
  kind: string;
  tenant_id: string;
}

export interface FieldDefinition {
  campaign_id: string | null;
  id: Generated<string>;
  key: string;
  tenant_id: string;
  value_type: string;
}

export interface ImportRecord {
  content_hash: string;
  entity_id: string;
  imported_at: Generated<Timestamp>;
  source: string;
  source_key: string;
  tenant_id: string;
}

export interface Tenant {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
}

export interface TranscriptSegment {
  campaign_id: string;
  end_ms: number;
  id: Generated<string>;
  session_no: number;
  speaker: string | null;
  start_ms: number;
  tenant_id: string;
  text: string;
  word_timings: Buffer;
}

export interface DB {
  campaign: Campaign;
  claim_current: ClaimCurrent;
  claim_embedding: ClaimEmbedding;
  claim_version: ClaimVersion;
  entity: Entity;
  field_definition: FieldDefinition;
  import_record: ImportRecord;
  tenant: Tenant;
  transcript_segment: TranscriptSegment;
}
