// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  CodecTypes as PgVectorTypes,
  Vector,
} from '@prisma/orm-extension-pgvector/codec-types';
import type { QueryOperationTypes as PgVectorQueryOperationTypes } from '@prisma/orm-extension-pgvector/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'b4c11737c4774575acc639908163c539bdba2997572ffa13f28883608db2f512'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes & PgVectorTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes> &
  PgVectorQueryOperationTypes<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Campaign: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly tenantId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly ClaimCurrent: {
      readonly campaignId: CodecTypes['pg/uuid@1']['output'];
      readonly claimId: CodecTypes['pg/uuid@1']['output'];
      readonly object: CodecTypes['pg/jsonb@1']['output'];
      readonly predicate: CodecTypes['pg/text@1']['output'];
      readonly subjectId: CodecTypes['pg/uuid@1']['output'];
      readonly tenantId: CodecTypes['pg/uuid@1']['output'];
      readonly version: CodecTypes['pg/int4@1']['output'];
    };
    readonly ClaimEmbedding: {
      readonly claimId: CodecTypes['pg/uuid@1']['output'];
      readonly tenantId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly ClaimVersion: {
      readonly campaignId: CodecTypes['pg/uuid@1']['output'];
      readonly claimId: CodecTypes['pg/uuid@1']['output'];
      readonly object: CodecTypes['pg/jsonb@1']['output'];
      readonly predicate: CodecTypes['pg/text@1']['output'];
      readonly recordedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly subjectId: CodecTypes['pg/uuid@1']['output'];
      readonly tenantId: CodecTypes['pg/uuid@1']['output'];
      readonly version: CodecTypes['pg/int4@1']['output'];
    };
    readonly Entity: {
      readonly campaignId: CodecTypes['pg/uuid@1']['output'];
      readonly custom: CodecTypes['pg/jsonb@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly kind: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly tenantId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly FieldDefinition: {
      readonly campaignId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly key: CodecTypes['pg/text@1']['output'];
      readonly tenantId: CodecTypes['pg/uuid@1']['output'];
      readonly valueType: CodecTypes['pg/text@1']['output'];
    };
    readonly ImportRecord: {
      readonly contentHash: CodecTypes['pg/text@1']['output'];
      readonly entityId: CodecTypes['pg/uuid@1']['output'];
      readonly importedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly source: CodecTypes['pg/text@1']['output'];
      readonly sourceKey: CodecTypes['pg/text@1']['output'];
      readonly tenantId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Tenant: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly TranscriptSegment: {
      readonly campaignId: CodecTypes['pg/uuid@1']['output'];
      readonly endMs: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly sessionNo: CodecTypes['pg/int4@1']['output'];
      readonly speaker: CodecTypes['pg/text@1']['output'] | null;
      readonly startMs: CodecTypes['pg/int4@1']['output'];
      readonly tenantId: CodecTypes['pg/uuid@1']['output'];
      readonly text: CodecTypes['pg/text@1']['output'];
      readonly wordTimings: CodecTypes['pg/bytea@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Campaign: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly tenantId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly ClaimCurrent: {
      readonly campaignId: CodecTypes['pg/uuid@1']['input'];
      readonly claimId: CodecTypes['pg/uuid@1']['input'];
      readonly object: CodecTypes['pg/jsonb@1']['input'];
      readonly predicate: CodecTypes['pg/text@1']['input'];
      readonly subjectId: CodecTypes['pg/uuid@1']['input'];
      readonly tenantId: CodecTypes['pg/uuid@1']['input'];
      readonly version: CodecTypes['pg/int4@1']['input'];
    };
    readonly ClaimEmbedding: {
      readonly claimId: CodecTypes['pg/uuid@1']['input'];
      readonly tenantId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly ClaimVersion: {
      readonly campaignId: CodecTypes['pg/uuid@1']['input'];
      readonly claimId: CodecTypes['pg/uuid@1']['input'];
      readonly object: CodecTypes['pg/jsonb@1']['input'];
      readonly predicate: CodecTypes['pg/text@1']['input'];
      readonly recordedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly subjectId: CodecTypes['pg/uuid@1']['input'];
      readonly tenantId: CodecTypes['pg/uuid@1']['input'];
      readonly version: CodecTypes['pg/int4@1']['input'];
    };
    readonly Entity: {
      readonly campaignId: CodecTypes['pg/uuid@1']['input'];
      readonly custom: CodecTypes['pg/jsonb@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly kind: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly tenantId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly FieldDefinition: {
      readonly campaignId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly key: CodecTypes['pg/text@1']['input'];
      readonly tenantId: CodecTypes['pg/uuid@1']['input'];
      readonly valueType: CodecTypes['pg/text@1']['input'];
    };
    readonly ImportRecord: {
      readonly contentHash: CodecTypes['pg/text@1']['input'];
      readonly entityId: CodecTypes['pg/uuid@1']['input'];
      readonly importedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly source: CodecTypes['pg/text@1']['input'];
      readonly sourceKey: CodecTypes['pg/text@1']['input'];
      readonly tenantId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Tenant: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly TranscriptSegment: {
      readonly campaignId: CodecTypes['pg/uuid@1']['input'];
      readonly endMs: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly sessionNo: CodecTypes['pg/int4@1']['input'];
      readonly speaker: CodecTypes['pg/text@1']['input'] | null;
      readonly startMs: CodecTypes['pg/int4@1']['input'];
      readonly tenantId: CodecTypes['pg/uuid@1']['input'];
      readonly text: CodecTypes['pg/text@1']['input'];
      readonly wordTimings: CodecTypes['pg/bytea@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly campaign: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly claim_current: {
      readonly campaign_id: CodecTypes['pg/uuid@1']['output'];
      readonly claim_id: CodecTypes['pg/uuid@1']['output'];
      readonly object: CodecTypes['pg/jsonb@1']['output'];
      readonly predicate: CodecTypes['pg/text@1']['output'];
      readonly subject_id: CodecTypes['pg/uuid@1']['output'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['output'];
      readonly version: CodecTypes['pg/int4@1']['output'];
    };
    readonly claim_embedding: {
      readonly claim_id: CodecTypes['pg/uuid@1']['output'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly claim_version: {
      readonly campaign_id: CodecTypes['pg/uuid@1']['output'];
      readonly claim_id: CodecTypes['pg/uuid@1']['output'];
      readonly object: CodecTypes['pg/jsonb@1']['output'];
      readonly predicate: CodecTypes['pg/text@1']['output'];
      readonly recorded_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly subject_id: CodecTypes['pg/uuid@1']['output'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['output'];
      readonly version: CodecTypes['pg/int4@1']['output'];
    };
    readonly entity: {
      readonly campaign_id: CodecTypes['pg/uuid@1']['output'];
      readonly custom: CodecTypes['pg/jsonb@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly kind: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly field_definition: {
      readonly campaign_id: CodecTypes['pg/uuid@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly key: CodecTypes['pg/text@1']['output'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['output'];
      readonly value_type: CodecTypes['pg/text@1']['output'];
    };
    readonly import_record: {
      readonly content_hash: CodecTypes['pg/text@1']['output'];
      readonly entity_id: CodecTypes['pg/uuid@1']['output'];
      readonly imported_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly source: CodecTypes['pg/text@1']['output'];
      readonly source_key: CodecTypes['pg/text@1']['output'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly tenant: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly transcript_segment: {
      readonly campaign_id: CodecTypes['pg/uuid@1']['output'];
      readonly end_ms: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly session_no: CodecTypes['pg/int4@1']['output'];
      readonly speaker: CodecTypes['pg/text@1']['output'] | null;
      readonly start_ms: CodecTypes['pg/int4@1']['output'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['output'];
      readonly text: CodecTypes['pg/text@1']['output'];
      readonly word_timings: CodecTypes['pg/bytea@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly campaign: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly claim_current: {
      readonly campaign_id: CodecTypes['pg/uuid@1']['input'];
      readonly claim_id: CodecTypes['pg/uuid@1']['input'];
      readonly object: CodecTypes['pg/jsonb@1']['input'];
      readonly predicate: CodecTypes['pg/text@1']['input'];
      readonly subject_id: CodecTypes['pg/uuid@1']['input'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['input'];
      readonly version: CodecTypes['pg/int4@1']['input'];
    };
    readonly claim_embedding: {
      readonly claim_id: CodecTypes['pg/uuid@1']['input'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly claim_version: {
      readonly campaign_id: CodecTypes['pg/uuid@1']['input'];
      readonly claim_id: CodecTypes['pg/uuid@1']['input'];
      readonly object: CodecTypes['pg/jsonb@1']['input'];
      readonly predicate: CodecTypes['pg/text@1']['input'];
      readonly recorded_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly subject_id: CodecTypes['pg/uuid@1']['input'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['input'];
      readonly version: CodecTypes['pg/int4@1']['input'];
    };
    readonly entity: {
      readonly campaign_id: CodecTypes['pg/uuid@1']['input'];
      readonly custom: CodecTypes['pg/jsonb@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly kind: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly field_definition: {
      readonly campaign_id: CodecTypes['pg/uuid@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly key: CodecTypes['pg/text@1']['input'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['input'];
      readonly value_type: CodecTypes['pg/text@1']['input'];
    };
    readonly import_record: {
      readonly content_hash: CodecTypes['pg/text@1']['input'];
      readonly entity_id: CodecTypes['pg/uuid@1']['input'];
      readonly imported_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly source: CodecTypes['pg/text@1']['input'];
      readonly source_key: CodecTypes['pg/text@1']['input'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly tenant: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly transcript_segment: {
      readonly campaign_id: CodecTypes['pg/uuid@1']['input'];
      readonly end_ms: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly session_no: CodecTypes['pg/int4@1']['input'];
      readonly speaker: CodecTypes['pg/text@1']['input'] | null;
      readonly start_ms: CodecTypes['pg/int4@1']['input'];
      readonly tenant_id: CodecTypes['pg/uuid@1']['input'];
      readonly text: CodecTypes['pg/text@1']['input'];
      readonly word_timings: CodecTypes['pg/bytea@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Campaign = {
    id: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    tenantId: CodecTypes['pg/uuid@1']['output'];
    claimCurrents: public_ClaimCurrent[];
    claimVersions: public_ClaimVersion[];
    entities: public_Entity[];
    fieldDefinitions: public_FieldDefinition[];
    tenant: public_Tenant;
    transcriptSegments: public_TranscriptSegment[];
    readonly [RelationKeys]?:
      | 'claimCurrents'
      | 'claimVersions'
      | 'entities'
      | 'fieldDefinitions'
      | 'tenant'
      | 'transcriptSegments';
  };
  export type public_ClaimCurrent = {
    campaignId: CodecTypes['pg/uuid@1']['output'];
    claimId: CodecTypes['pg/uuid@1']['output'];
    object: CodecTypes['pg/jsonb@1']['output'];
    predicate: CodecTypes['pg/text@1']['output'];
    subjectId: CodecTypes['pg/uuid@1']['output'];
    tenantId: CodecTypes['pg/uuid@1']['output'];
    version: CodecTypes['pg/int4@1']['output'];
    campaign: public_Campaign;
    claimEmbedding: public_ClaimEmbedding | null;
    entity: public_Entity;
    readonly [RelationKeys]?: 'campaign' | 'claimEmbedding' | 'entity';
  };
  export type public_ClaimEmbedding = {
    claimId: CodecTypes['pg/uuid@1']['output'];
    tenantId: CodecTypes['pg/uuid@1']['output'];
    claimCurrent: public_ClaimCurrent;
    readonly [RelationKeys]?: 'claimCurrent';
  };
  export type public_ClaimVersion = {
    campaignId: CodecTypes['pg/uuid@1']['output'];
    claimId: CodecTypes['pg/uuid@1']['output'];
    object: CodecTypes['pg/jsonb@1']['output'];
    predicate: CodecTypes['pg/text@1']['output'];
    recordedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    subjectId: CodecTypes['pg/uuid@1']['output'];
    tenantId: CodecTypes['pg/uuid@1']['output'];
    version: CodecTypes['pg/int4@1']['output'];
    campaign: public_Campaign;
    entity: public_Entity;
    readonly [RelationKeys]?: 'campaign' | 'entity';
  };
  export type public_Entity = {
    campaignId: CodecTypes['pg/uuid@1']['output'];
    custom: CodecTypes['pg/jsonb@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    kind: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    tenantId: CodecTypes['pg/uuid@1']['output'];
    campaign: public_Campaign;
    claimCurrents: public_ClaimCurrent[];
    claimVersions: public_ClaimVersion[];
    importRecords: public_ImportRecord[];
    readonly [RelationKeys]?: 'campaign' | 'claimCurrents' | 'claimVersions' | 'importRecords';
  };
  export type public_FieldDefinition = {
    campaignId: CodecTypes['pg/uuid@1']['output'] | null;
    id: CodecTypes['pg/uuid@1']['output'];
    key: CodecTypes['pg/text@1']['output'];
    tenantId: CodecTypes['pg/uuid@1']['output'];
    valueType: CodecTypes['pg/text@1']['output'];
    campaign: public_Campaign | null;
    tenant: public_Tenant;
    readonly [RelationKeys]?: 'campaign' | 'tenant';
  };
  export type public_ImportRecord = {
    contentHash: CodecTypes['pg/text@1']['output'];
    entityId: CodecTypes['pg/uuid@1']['output'];
    importedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    source: CodecTypes['pg/text@1']['output'];
    sourceKey: CodecTypes['pg/text@1']['output'];
    tenantId: CodecTypes['pg/uuid@1']['output'];
    entity: public_Entity;
    tenant: public_Tenant;
    readonly [RelationKeys]?: 'entity' | 'tenant';
  };
  export type public_Tenant = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    campaigns: public_Campaign[];
    fieldDefinitions: public_FieldDefinition[];
    importRecords: public_ImportRecord[];
    readonly [RelationKeys]?: 'campaigns' | 'fieldDefinitions' | 'importRecords';
  };
  export type public_TranscriptSegment = {
    campaignId: CodecTypes['pg/uuid@1']['output'];
    endMs: CodecTypes['pg/int4@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    sessionNo: CodecTypes['pg/int4@1']['output'];
    speaker: CodecTypes['pg/text@1']['output'] | null;
    startMs: CodecTypes['pg/int4@1']['output'];
    tenantId: CodecTypes['pg/uuid@1']['output'];
    text: CodecTypes['pg/text@1']['output'];
    wordTimings: CodecTypes['pg/bytea@1']['output'];
    campaign: public_Campaign;
    readonly [RelationKeys]?: 'campaign';
  };
}

export declare const models: {
  public: {
    Campaign: Models.public_Campaign;
    ClaimCurrent: Models.public_ClaimCurrent;
    ClaimEmbedding: Models.public_ClaimEmbedding;
    ClaimVersion: Models.public_ClaimVersion;
    Entity: Models.public_Entity;
    FieldDefinition: Models.public_FieldDefinition;
    ImportRecord: Models.public_ImportRecord;
    Tenant: Models.public_Tenant;
    TranscriptSegment: Models.public_TranscriptSegment;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly campaign: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'uuidv7()' };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tenant_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['tenant_id', 'id'];
                readonly name: 'campaign_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campaign';
                    readonly columns: readonly ['tenant_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tenant';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'campaign_tenant_id_fkey';
                },
              ];
            };
            readonly claim_current: {
              columns: {
                readonly campaign_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly claim_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly object: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly predicate: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly subject_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly tenant_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly version: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['tenant_id', 'claim_id'];
                readonly name: 'claim_current_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'claim_current_subject_idx';
                  readonly columns: readonly ['tenant_id', 'subject_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'claim_current';
                    readonly columns: readonly ['tenant_id', 'campaign_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campaign';
                    readonly columns: readonly ['tenant_id', 'id'];
                  };
                  readonly name: 'claim_current_tenant_id_campaign_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'claim_current';
                    readonly columns: readonly ['tenant_id', 'subject_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'entity';
                    readonly columns: readonly ['tenant_id', 'id'];
                  };
                  readonly name: 'claim_current_tenant_id_subject_id_fkey';
                },
              ];
            };
            readonly claim_embedding: {
              columns: {
                readonly claim_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly tenant_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['tenant_id', 'claim_id'];
                readonly name: 'claim_embedding_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'claim_embedding';
                    readonly columns: readonly ['tenant_id', 'claim_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'claim_current';
                    readonly columns: readonly ['tenant_id', 'claim_id'];
                  };
                  readonly name: 'claim_embedding_tenant_id_claim_id_fkey';
                },
              ];
            };
            readonly claim_version: {
              columns: {
                readonly campaign_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly claim_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly object: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly predicate: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly recorded_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly subject_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly tenant_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly version: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['tenant_id', 'claim_id', 'version'];
                readonly name: 'claim_version_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'claim_version';
                    readonly columns: readonly ['tenant_id', 'campaign_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campaign';
                    readonly columns: readonly ['tenant_id', 'id'];
                  };
                  readonly name: 'claim_version_tenant_id_campaign_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'claim_version';
                    readonly columns: readonly ['tenant_id', 'subject_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'entity';
                    readonly columns: readonly ['tenant_id', 'id'];
                  };
                  readonly name: 'claim_version_tenant_id_subject_id_fkey';
                },
              ];
            };
            readonly entity: {
              columns: {
                readonly campaign_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly custom: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/jsonb@1', {}>;
                  };
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'uuidv7()' };
                };
                readonly kind: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tenant_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['tenant_id', 'id'];
                readonly name: 'entity_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'entity_campaign_idx';
                  readonly columns: readonly ['tenant_id', 'campaign_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'entity';
                    readonly columns: readonly ['tenant_id', 'campaign_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campaign';
                    readonly columns: readonly ['tenant_id', 'id'];
                  };
                  readonly name: 'entity_tenant_id_campaign_id_fkey';
                },
              ];
            };
            readonly field_definition: {
              columns: {
                readonly campaign_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'uuidv7()' };
                };
                readonly key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tenant_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly value_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['tenant_id', 'id'];
                readonly name: 'field_definition_pkey';
              };
              uniques: readonly [
                {
                  readonly columns: readonly ['tenant_id', 'campaign_id', 'key'];
                  readonly name: 'field_definition_tenant_id_campaign_id_key_key';
                },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'field_definition';
                    readonly columns: readonly ['tenant_id', 'campaign_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campaign';
                    readonly columns: readonly ['tenant_id', 'id'];
                  };
                  readonly name: 'field_definition_tenant_id_campaign_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'field_definition';
                    readonly columns: readonly ['tenant_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tenant';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'field_definition_tenant_id_fkey';
                },
              ];
            };
            readonly import_record: {
              columns: {
                readonly content_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly entity_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly imported_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly source: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly source_key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tenant_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['tenant_id', 'source', 'source_key'];
                readonly name: 'import_record_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'import_record';
                    readonly columns: readonly ['tenant_id', 'entity_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'entity';
                    readonly columns: readonly ['tenant_id', 'id'];
                  };
                  readonly name: 'import_record_tenant_id_entity_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'import_record';
                    readonly columns: readonly ['tenant_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tenant';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'import_record_tenant_id_fkey';
                },
              ];
            };
            readonly tenant: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'uuidv7()' };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'tenant_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly transcript_segment: {
              columns: {
                readonly campaign_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly end_ms: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'uuidv7()' };
                };
                readonly session_no: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly speaker: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly start_ms: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly tenant_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly word_timings: {
                  readonly nativeType: 'bytea';
                  readonly codecId: 'pg/bytea@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['tenant_id', 'id'];
                readonly name: 'transcript_segment_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'transcript_segment_session_idx';
                  readonly columns: readonly ['tenant_id', 'campaign_id', 'session_no', 'start_ms'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'transcript_segment';
                    readonly columns: readonly ['tenant_id', 'campaign_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'campaign';
                    readonly columns: readonly ['tenant_id', 'id'];
                  };
                  readonly name: 'transcript_segment_tenant_id_campaign_id_fkey';
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly campaign: { readonly namespace: 'public' & NamespaceId; readonly model: 'Campaign' };
    readonly claim_current: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ClaimCurrent';
    };
    readonly claim_embedding: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ClaimEmbedding';
    };
    readonly claim_version: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ClaimVersion';
    };
    readonly entity: { readonly namespace: 'public' & NamespaceId; readonly model: 'Entity' };
    readonly field_definition: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'FieldDefinition';
    };
    readonly import_record: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ImportRecord';
    };
    readonly tenant: { readonly namespace: 'public' & NamespaceId; readonly model: 'Tenant' };
    readonly transcript_segment: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'TranscriptSegment';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Campaign: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly claimCurrents: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ClaimCurrent';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'id'];
                  readonly targetFields: readonly ['tenantId', 'campaignId'];
                };
              };
              readonly claimVersions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ClaimVersion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'id'];
                  readonly targetFields: readonly ['tenantId', 'campaignId'];
                };
              };
              readonly entities: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Entity';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'id'];
                  readonly targetFields: readonly ['tenantId', 'campaignId'];
                };
              };
              readonly fieldDefinitions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FieldDefinition';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'id'];
                  readonly targetFields: readonly ['tenantId', 'campaignId'];
                };
              };
              readonly tenant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Tenant';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly transcriptSegments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'TranscriptSegment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'id'];
                  readonly targetFields: readonly ['tenantId', 'campaignId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'campaign';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly tenantId: { readonly column: 'tenant_id' };
              };
            };
          };
          readonly ClaimCurrent: {
            readonly fields: {
              readonly campaignId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly claimId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly object: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly predicate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly subjectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly version: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly campaign: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Campaign';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'campaignId'];
                  readonly targetFields: readonly ['tenantId', 'id'];
                };
              };
              readonly claimEmbedding: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ClaimEmbedding';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'claimId'];
                  readonly targetFields: readonly ['tenantId', 'claimId'];
                };
              };
              readonly entity: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Entity';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'subjectId'];
                  readonly targetFields: readonly ['tenantId', 'id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'claim_current';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly campaignId: { readonly column: 'campaign_id' };
                readonly claimId: { readonly column: 'claim_id' };
                readonly object: { readonly column: 'object' };
                readonly predicate: { readonly column: 'predicate' };
                readonly subjectId: { readonly column: 'subject_id' };
                readonly tenantId: { readonly column: 'tenant_id' };
                readonly version: { readonly column: 'version' };
              };
            };
          };
          readonly ClaimEmbedding: {
            readonly fields: {
              readonly claimId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly claimCurrent: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ClaimCurrent';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'claimId'];
                  readonly targetFields: readonly ['tenantId', 'claimId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'claim_embedding';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly claimId: { readonly column: 'claim_id' };
                readonly tenantId: { readonly column: 'tenant_id' };
              };
            };
          };
          readonly ClaimVersion: {
            readonly fields: {
              readonly campaignId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly claimId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly object: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly predicate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly recordedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly subjectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly version: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly campaign: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Campaign';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'campaignId'];
                  readonly targetFields: readonly ['tenantId', 'id'];
                };
              };
              readonly entity: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Entity';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'subjectId'];
                  readonly targetFields: readonly ['tenantId', 'id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'claim_version';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly campaignId: { readonly column: 'campaign_id' };
                readonly claimId: { readonly column: 'claim_id' };
                readonly object: { readonly column: 'object' };
                readonly predicate: { readonly column: 'predicate' };
                readonly recordedAt: { readonly column: 'recorded_at' };
                readonly subjectId: { readonly column: 'subject_id' };
                readonly tenantId: { readonly column: 'tenant_id' };
                readonly version: { readonly column: 'version' };
              };
            };
          };
          readonly Entity: {
            readonly fields: {
              readonly campaignId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly custom: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly campaign: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Campaign';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'campaignId'];
                  readonly targetFields: readonly ['tenantId', 'id'];
                };
              };
              readonly claimCurrents: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ClaimCurrent';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'id'];
                  readonly targetFields: readonly ['tenantId', 'subjectId'];
                };
              };
              readonly claimVersions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ClaimVersion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'id'];
                  readonly targetFields: readonly ['tenantId', 'subjectId'];
                };
              };
              readonly importRecords: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ImportRecord';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'id'];
                  readonly targetFields: readonly ['tenantId', 'entityId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'entity';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly campaignId: { readonly column: 'campaign_id' };
                readonly custom: { readonly column: 'custom' };
                readonly id: { readonly column: 'id' };
                readonly kind: { readonly column: 'kind' };
                readonly name: { readonly column: 'name' };
                readonly tenantId: { readonly column: 'tenant_id' };
              };
            };
          };
          readonly FieldDefinition: {
            readonly fields: {
              readonly campaignId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly valueType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly campaign: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Campaign';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'campaignId'];
                  readonly targetFields: readonly ['tenantId', 'id'];
                };
              };
              readonly tenant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Tenant';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'field_definition';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly campaignId: { readonly column: 'campaign_id' };
                readonly id: { readonly column: 'id' };
                readonly key: { readonly column: 'key' };
                readonly tenantId: { readonly column: 'tenant_id' };
                readonly valueType: { readonly column: 'value_type' };
              };
            };
          };
          readonly ImportRecord: {
            readonly fields: {
              readonly contentHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly entityId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly importedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sourceKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly entity: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Entity';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'entityId'];
                  readonly targetFields: readonly ['tenantId', 'id'];
                };
              };
              readonly tenant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Tenant';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'import_record';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly contentHash: { readonly column: 'content_hash' };
                readonly entityId: { readonly column: 'entity_id' };
                readonly importedAt: { readonly column: 'imported_at' };
                readonly source: { readonly column: 'source' };
                readonly sourceKey: { readonly column: 'source_key' };
                readonly tenantId: { readonly column: 'tenant_id' };
              };
            };
          };
          readonly Tenant: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly campaigns: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Campaign';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tenantId'];
                };
              };
              readonly fieldDefinitions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FieldDefinition';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tenantId'];
                };
              };
              readonly importRecords: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ImportRecord';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tenantId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'tenant';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly TranscriptSegment: {
            readonly fields: {
              readonly campaignId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly endMs: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly sessionNo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly speaker: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startMs: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly text: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly wordTimings: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bytea@1' };
              };
            };
            readonly relations: {
              readonly campaign: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Campaign';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['tenantId', 'campaignId'];
                  readonly targetFields: readonly ['tenantId', 'id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'transcript_segment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly campaignId: { readonly column: 'campaign_id' };
                readonly endMs: { readonly column: 'end_ms' };
                readonly id: { readonly column: 'id' };
                readonly sessionNo: { readonly column: 'session_no' };
                readonly speaker: { readonly column: 'speaker' };
                readonly startMs: { readonly column: 'start_ms' };
                readonly tenantId: { readonly column: 'tenant_id' };
                readonly text: { readonly column: 'text' };
                readonly wordTimings: { readonly column: 'word_timings' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly 'pgvector.cosine': true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {
    readonly pgvector: {
      readonly capabilities: { readonly postgres: { readonly 'pgvector.cosine': true } };
      readonly familyId: 'sql';
      readonly id: 'pgvector';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: 'PgVectorTypes';
            readonly named: 'CodecTypes';
            readonly package: '@internal/extension-pgvector/codec-types';
          };
          readonly typeImports: readonly [
            {
              readonly alias: 'Vector';
              readonly named: 'Vector';
              readonly package: '@internal/extension-pgvector/codec-types';
            },
          ];
        };
        readonly operationTypes: {
          readonly import: {
            readonly alias: 'PgVectorOperationTypes';
            readonly named: 'OperationTypes';
            readonly package: '@internal/extension-pgvector/operation-types';
          };
        };
        readonly queryOperationTypes: {
          readonly import: {
            readonly alias: 'PgVectorQueryOperationTypes';
            readonly named: 'QueryOperationTypes';
            readonly package: '@internal/extension-pgvector/operation-types';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'vector';
            readonly targetId: 'postgres';
            readonly typeId: 'pg/vector@1';
          },
        ];
      };
      readonly version: '0.0.1';
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
